# This is a basic workflow to help you get started with Actions

name: CI-OIDC

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# promote some secrets to environment
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prepare:
    - name: Get Droppings via reusable workflow
      uses: shards-of-blue/moose-droppings/.github/workflows/import.yml@master
      with:
        targetdir: ${{ github.workspace }}

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo env dump
          env
          echo 'BASE64(TOKEN):'
          echo ${{ secrets.GITHUB_TOKEN }} | base64
          echo 'BASE64(OIDCTOKEN):'
          echo ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }} | base64
          echo URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
          ls -la

#      - name: Get Droppings via action
#        uses: shards-of-blue/moose-droppings@master
#        with:
#          env: 'test'

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          #azcliversion: 2.37.0
          inlineScript: |
            az version
            az account show
            az storage -h
            az keyvault list
